---
name: RHEL 8.3 on ESXi 7.0

on:
  pull_request:
    branches:
      - "*"

jobs:
  esxi_bios:
    name: Run test on ESXi 7.0 VM (BIOS)
    runs-on: kite-runner

    steps:
      - name: Checkout kite-test repository
        uses: actions/checkout@v2

      - name: Checkout kite-deploy repository
        uses: actions/checkout@v2
        with:
          repository: virt-s1/kite-deploy
          path: kite-deploy

      - name: Deploy ESXi BIOS VM
        run: cd kite-deploy && ansible-playbook -v -i inventory -e esxi_firmware=bios -e cloud_platform=esxi deploy.yaml

      - name: Run test
        run: |
          GUEST_IP=$(awk -F "=" '/guest_ip/ {print $2}' kite-deploy/inventory)
          test/check-ltp -vst --user=admin --address=$GUEST_IP

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: ltp-logs
          path: ./log

      - uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: test-log
          path: ./Test*FAIL.log.gz

      # - name: Remove ESXi VM
      #   if: ${{ always() }}
      #   run: cd kite-deploy && ansible-playbook -v -i inventory -e cloud_platform=esxi remove.yaml

      - name: Remove runner
        if: ${{ always() }}
        run: |
          RUNNER_NAME=$(cat /etc/hostname)
          curl -X PUT $KITE_CONTROLLER_API_NETLOC/runner/delete/$RUNNER_NAME > /dev/null 2>&1 &
